### ISSUE TITLE
Rights serializer does not include all fields for some bases, and too many fields for other bases

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/aquila#125]
The rights serializer creates JSON that does not successfully validate against the RAC schema because it does not include fields that are mandatory for specific bases. Further, the rights serializer should _not_ include fields that do not apply to a specific basis. See this test as an example:

```
Failed validating 'required' in schema['allOf'][0]['allOf'][1]:
    {'properties': {'jurisdiction': {'examples': ['fr'],
                                     'pattern': '^[a-z]{2}$',
                                     'title': 'Rights Basis Statute '
                                              'Jurisdiction',
                                     'type': 'string'},
                    'rights_basis': {'enum': ['statute']},
                    'statute_citation': {'minLength': 1,
                                         'title': 'Statute Citation',
                                         'type': 'string'}},
     'required': ['jurisdiction', 'statute_citation']}

On instance:
    {'citation': 'hhSIBPTwoovdlEzNTfvp',
     'copyright_status': None,
     'determination_date': '2019-04-02',
     'end_date': '1982-04-02',
     'jurisdiction': 'us',
     'note': 'EYiXdpWctiKtMMRycesS',
     'rights_basis': 'statute',
     'rights_granted': [],
     'start_date': '1949-04-02',
     'status': None,
     'terms': None}
```

The rights serializer should be able to produce JSON that only contains the fields specific to a given rights basis.

**Comment by helrond** [comment]
Changes made to rights statements should be checked against the structure Fornax expects to receive, as well as what is produced in Aurora. Ultimately we'll need to align all of these representations, so that we can effectively validate in Ursa Major (currently using a very out of date version of rac_schemas).
