### ISSUE TITLE
Add home page

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/aquila#142]
## Is your feature request related to a problem? Please describe.
Currently, users land on the "grouping" page when they open the application. This can be confusing.

## Describe the solution you'd like
Add a "home page" that a user lands on upon logging in.

**Comment by helrond** [comment]
@bonniegee do you have any additional information in your notes about what should be on this page? Happy to work on this, but need a bit of a reminder as to what we talked about this page looking like...

**Comment by bonniegee** [comment]
From my notes: "Have a splash page that people land on that gives info about what's going on "

That's not very descriptive! Users will primarily be doing 4 things in this application: browsing groupings, creating groupings, browsing rights shells, and creating rights shells. A splash page could link to (or describe) those four actions?

**Comment by HaSistrunk** [comment]
We discussed links to the RAC PREMIS documentation, and I _think_ decided not too because of the nature of the documentation. Is that right? https://docs.rockarch.org/premis-rights-guidelines/

**Comment by bonniegee** [comment]
That sounds right to me @HaSistrunk

**Comment by p-galligan** [comment]
I'm pretty sure we decided against it because our RAC premis guidelines because they're not really _full_ documentation.
