### ISSUE TITLE
Set up user who can modify users' permissions

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/aquila#158]
## Is your feature request related to a problem? Please describe.
There is no way for one user to modify the permissions of other users. Right now, you need to manually create a [super user](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Admin_site#creating_a_superuser) and log in as that user in order to give any other account permission to see the Django admin site and modify other users permissions.

When running in production, we'll use single sign-on (see #37), so while we will not need to manually create new users, we will need to modify their permissions.

## Describe the solution you'd like
On setup, there needs to be an initial account created that has the `assign_rights | user` permissions enabled.

## Additional context
Given the small number of users of this application, and that any additional users will be rarely added at all (let alone need additional permissions), using the Django admin site is sufficient for managing user permissions.

**Comment by helrond** [comment]
@bonniegee can you clarify how this differs from the current setup? Are you looking to get rid of the superuser and replace that account with one that has more limited permissions? Or do you want to add another one?

**Comment by bonniegee** [comment]
Currently, the user created on setup does not have those permissions enabled. Would it be easier for deployment if a user with those permissions was created automatically?

**Comment by helrond** [comment]
Ah I see - I thought the user being created was a superuser.
