### ISSUE TITLE
Users with view-only permissions can see (and click on) "create" buttons on home page

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/aquila#170]
## Describe the bug
If a user does not have permissions to "create" a new rights shell or grouping, they are still able to see the "create" buttons on the homepage. When that user clicks on one of the buttons, they are taken to a 403 error page.

## To reproduce
1. Login as a user who is not part of the "edit" group
2. Go to the home page
3. Click on the "Create a new grouping" or "Create a new rights statement" page

## Expected behavior
Users who cannot "create" new records should not be able to see the related buttons (or the related buttons can be disabled).

## Error message or screenshots
<img width="1435" alt="Screen Shot 2021-06-22 at 18 37 28" src="https://user-images.githubusercontent.com/8737364/123008459-e7a07e00-d388-11eb-8928-e9e4f3cb9af0.png">

**Comment by p-galligan** [comment]
FYI, I think you can do this pretty easily with the [has_group](https://stackoverflow.com/questions/34571880/how-to-check-in-template-if-user-belongs-to-a-group) functionality.
