### ISSUE TITLE
"note" field should be "basis_note"

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/aquila#182]
## Is your feature request related to a problem? Please describe.
Fornax is currently creating a "note" field in rights JSON, but the field according to `rac_schemas` should be "basis_note"

## Describe the solution you'd like
Update the rights basis model to include "basis_note" instead of "note."

## Additional context
See RockefellerArchiveCenter/fornax#180

**Comment by helrond** [comment]
We'll need to change serializers too.

**Comment by bonniegee** [comment]
We'll also need to change "note" to "granted_note" for rights granted or restricted.
