### ISSUE TITLE
User permissions reverting when development deployment is updated

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/aquila#184]
## Describe the bug
Documenting this now to dig into later--

It seems like every time the app is updated (we have CI/CD set up on our development deployment), my user account's permissions fall back to the minimum allowed.

## To reproduce
Set up an account on our development instance with more than minimal permissions. After application is updated, check again.

## Expected behavior
A user's permissions stay the same after each deploy.

**Comment by helrond** [comment]
Have not had time to test this theory yet, but I'm wondering if it's related to the `GROUPS_CLAIM` setting (see the "Important") note: https://django-auth-adfs.readthedocs.io/en/latest/settings_ref.html#groups-claim

**Comment by helrond** [comment]
Fixed by #186
