### ISSUE TITLE
Add user groups or some other mechanism of managing access

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/aquila#44]
## Is your feature request related to a problem? Please describe.
Now that we've implemented SSO, any user can get into Aquila and do things with just their windows username and password. This is non-optimal.

## Describe the solution you'd like
Add user groups or some other method of managing user access more granularly. 

## Additional context
This may mean we want to add additional features to the app, such as the ability for sys admins to add and remove users from groups. We'll also need to consider carefully what groups we want and what permissions should be assigned to each.

**Comment by bonniegee** [comment]
I think there needs to be at least 3 groups of users:

- Users who can search and view groupings and rights statements
- Users who can search, view, create, and update groupings and rights statements
- Users who can search, view, create, update, and delete groupings and rights statements, and manage users

To your point about anyone being able to log in, I'm wondering if there should be a user default who can't view anything. What are your thoughts?

**Comment by helrond** [comment]
Well, I'm not sure there's anything super confidential in this app, so I wouldn't be opposed to the base permission being the first one you describe above (read-only access). I think it's more when we get into create/update/delete actions that we'll likely want a bit more control.

**Comment by p-galligan** [comment]
@bonniegee Can a user be part of more than one group at once? (I don't think it'd be necessary given what's outlined above, but it would slightly impact work)

**Comment by bonniegee** [comment]
Good question! Let's go with no: a user can be part of only one group.
