### ISSUE TITLE
Prevent rights basis type from changing on the edit page

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/aquila#64]
## Is your feature request related to a problem? Please describe.
On both the create and edit page, fields are rendered in the form depending on what rights basis is selected. If a rights basis type changes in the edit page, there could be issues relating to the different fields that display for each type and validation.

## Describe the solution you'd like
Disable rights basis drop down if editing, and not creating, a rights statement shell.

**Comment by helrond** [comment]
This is definitely the simplest implementation. It should be possible, however, to deal with these validation issues, particularly since a lot of it is happening in Javascript. But you can wait and see whether user testing indicates a more complex approach is necessary.
