### ISSUE TITLE
Loop through IDs from POST request, retrieve rights shells

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/aquila#8]
For each Rights Shell ID in the POST request, retrieve the rights shell (including the calculation rules)

**Comment by p-galligan** [comment]
@bonniegee Is there already a view in place to handle this data? If so, which one?

I'm basically trying to figure out how where the `retrieve_rights` assembly method is getting its information.

**Comment by bonniegee** [comment]
There isn't a view in place to handle this data yet; there needs to be [an APIView](https://www.django-rest-framework.org/api-guide/views/) added.
