### ISSUE TITLE
Improve str method for RightsShells

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/aquila#80]
## Is your feature request related to a problem? Please describe.
The `str` method determines the string that is displayed for model instances in multi-select fields, such as the multi-select for RightsShells in the Groupings create and edit forms. For rights shells, this is currently set to `"{} ({})".format(self.note, self.rights_basis)`, which does not always provide the necessary information.

## Describe the solution you'd like
Provide a better display string. Consider using additional basis information as well as act/restriction information.

## Additional considerations
We may want to make additional fields required in the rights basis and/or rights granted model. In particular, it seems like the note could be a potentially useful field in helping humans disambiguate rights statements and we may want to make that required even though it's optional in PREMIS.

**Comment by bonniegee** [comment]
I think in addition to, or as a substitute for, note content, the rights granted associated with a basis would be helpful in disambiguating rights statements. However, as there can be zero, one, or multiple acts associated with a basis, I'm not sure if that's compatible with the `__str__` method?

**Comment by helrond** [comment]
That could work - the `__str__` method would just have to account for those cases.
