### ISSUE TITLE
Should rights bases be lowercase?

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/aquila#94]
## Is your feature request related to a problem? Please describe.
The database and display values for rights bases are both title-cased. Unless there's a good reason for it, the value we store in the database should *probably* be normalized i.e. lowercase.

## Describe the solution you'd like
If this wasn't a conscious choice, change the first value of the `RIGHTS_BASIS_CHOICES` tuple to lowercase. This will also require a new migration.

## Describe alternatives you've considered
If there's a reason for leaving as-is, let's leave it alone!

**Comment by bonniegee** [comment]
These can definitely be made lower case.
