### ISSUE TITLE
Improve form error indications for rights basis

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/aquila#96]
## Is your feature request related to a problem? Please describe.
If there is an error in the form (like the start date is in the wrong format), and the user tries to save, they have to restart the form to see where the error occurred.

## Describe the solution you'd like
Given the approach we're using, I'm not sure what the best solution here is. At minimum, a message indicating that their were errors preventing submission that the user can see when they try and  fail to save would reduce confusion.

**Comment by helrond** [comment]
I think that this and #67 should probably be looked at together.
